services:
  - type: web
    name: flixora-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        value: 8914900872:AAHZVd2EHww1KwnGFQaEOjPeYI9l02nT7Ms
      - key: PORT
        value: "10000"